### PR TITLE
Reorder package.json

### PR DESCRIPTION
**Pull request by jstarry**

### CODE REVIEW

**Comment by camacho** [comment]
What's the rational behind the re-order?

**Comment by jstarry** [comment]
When you npm install --save-dev a new package it will automatically reorder these

**Comment by camacho** [comment]
yea, just not clear the point of this PR. doesn't look like any packages were added, so was the re-order done by hand? if so, can you help me understand why?

**Comment by jstarry** [comment]
whenever npm installs a new dev dependency, it automatically alphabetizes the packages. Currently the packages aren't correctly alphabetized. Any subsequent call to npm install --save-dev package-name will rearrange these entries (that I rearranged manually for this PR)

**Comment by camacho** [comment]
Ok, gtg

**Pull request merged**
